version: "3"

services:
  console:
    build: ./
    command:
      - play
    entrypoint:
      - bin/console
    environment:
      APP_ENV: production
    networks:
      - default
    stdin_open: true
    tty: true
    volumes:
      - games:/usr/src/chess/var/games

  web:
    depends_on:
      - api
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - ./docker/web/api.conf:/etc/nginx/conf.d/default.conf
      - ./public:/usr/src/chess/public

  api:
    build:
      context: .
      dockerfile: Dockerfile-api
    environment:
      APP_ENV: prod
    networks:
      - default
    volumes:
      - games:/usr/src/chess/var/games

  dev:
    build: ./
    command: composer install --no-interaction
    networks:
      - default
    stdin_open: true
    tty: true
    volumes:
      - ./docker/dev/.bashrc:/root/.bashrc
      - ./:/usr/src/chess

networks:
  default:

volumes:
  games: